## Animations Sandbox

In [1]:
import numpy as np
np.cross([1, 1], [2, 3])

array(1)

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [19]:
pixels = np.zeros([3, 2])
pixels

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
pixels[0][0] = 1
pixels

array([[1., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
height, side = 3, 3
pixels = np.zeros((int(height), int(side), 3), np.uint8)
pixels[:] = (0, 255, 0)
pixels

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)

In [31]:
pixels[0][0] = (3, 4, 5)
pixels

array([[[  3,   4,   5],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)

In [32]:
np.linalg.norm([499.21225409 -14.42434659])

484.78790749999996

In [33]:
min(1, 2, 3)

1

In [2]:
import numpy as np
l = [np.array([1, 1, 1]), np.array([4, 5, 6])]
l = np.array(l).reshape()

[array([1, 1, 1]), array([4, 5, 6])]

In [29]:
halfwidth = 6 # total width is 12
spacing = 1
n_spaces = int(2*halfwidth/spacing)-1
du = 0.1
for u in np.arange(0, 1+du, du):
    print(-halfwidth + np.round(u*n_spaces)*spacing)

-6.0
-5.0
-4.0
-3.0
-2.0
0.0
1.0
2.0
3.0
4.0
5.0


In [7]:
[-0.5, -0.5+0.4, -0.5+0.8, -0.5+0.8+0.4]

[-0.5, -0.09999999999999998, 0.30000000000000004, 0.7000000000000001]

In [6]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])