## Animations Sandbox

In [1]:
import numpy as np
np.cross([1, 1], [2, 3])

array(1)

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [19]:
pixels = np.zeros([3, 2])
pixels

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
pixels[0][0] = 1
pixels

array([[1., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
height, side = 3, 3
pixels = np.zeros((int(height), int(side), 3), np.uint8)
pixels[:] = (0, 255, 0)
pixels

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)

In [31]:
pixels[0][0] = (3, 4, 5)
pixels

array([[[  3,   4,   5],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]], dtype=uint8)

In [32]:
np.linalg.norm([499.21225409 -14.42434659])

484.78790749999996

In [33]:
min(1, 2, 3)

1

In [2]:
import numpy as np
l = [np.array([1, 1, 1]), np.array([4, 5, 6])]
l = np.array(l).reshape()

[array([1, 1, 1]), array([4, 5, 6])]

In [29]:
halfwidth = 6 # total width is 12
spacing = 1
n_spaces = int(2*halfwidth/spacing)-1
du = 0.1
for u in np.arange(0, 1+du, du):
    print(-halfwidth + np.round(u*n_spaces)*spacing)

-6.0
-5.0
-4.0
-3.0
-2.0
0.0
1.0
2.0
3.0
4.0
5.0


In [7]:
[-0.5, -0.5+0.4, -0.5+0.8, -0.5+0.8+0.4]

[-0.5, -0.09999999999999998, 0.30000000000000004, 0.7000000000000001]

In [6]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [10]:
R = np.array([
    [1, 2],
    [0, 1]
])

v = np.array([1, 2])
np.dot(R, v)

array([5, 2])

In [11]:
import os
from PIL import Image

# Set the input and output directories
main_dir = '/Users/adityaabhyankar/Desktop/Programming/Animations/output'
ps_files_dir = main_dir + '/Postscript Frames'
png_files_dir = main_dir + '/Png Frames'

# Iterate over all the files in the input directory
for filename in os.listdir(ps_dir):
    if filename.endswith('.ps'):
        # Open the PostScript file and create an Image object
        with Image.open(os.path.join(ps_files_dir, filename)) as img:
            # Convert the Image object to PNG format
            png_filename = os.path.splitext(filename)[0] + '.png'
            png_path = os.path.join(png_files_dir, png_filename)
            img.convert('RGB').save(png_path)

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_imaging.cpython-310-darwin.so' (no such file)

In [7]:
# import sympy
from sympy import *

M = Matrix([[1, 0, -1, 0],
            [2, 0, -3, -1],
            [0, 2, 0, -1],
            [0, 1, 0, -1]])
print("Matrix : {} ".format(M))

# Use sympy.rref() method
M_rref = M.rref()
	
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))


# Conjecture: Chemical equation cannot be balanced iff the rref of the associated matrix is the identity cuz then the kernel is trivial.

Matrix : Matrix([[1, 0, -1, 0], [2, 0, -3, -1], [0, 2, 0, -1], [0, 1, 0, -1]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]), (0, 1, 2, 3))


In [21]:
import sympy as sp

# Create the matrix
A = sp.Matrix([[1, 2, 3, 0, 0, 0], [4, 5, 6, 0, 0, 0], [7, 8, 9, 0, 0, 0]])

# Compute the reduced row echelon form with steps
rref_steps = A.rref(simplify=True, pivots=False)

# Print every step of the row reduction process
for i, step in enumerate(rref_steps):
    print(f"Step {i+1}:")
    for row in step.tolist():
        print("  " + str(row))
    print()
    
# Print the final reduced row echelon form
print("Final result:")
for row in rref_steps.tolist():
    print("  " + str(row))


Step 1:


AttributeError: 'One' object has no attribute 'tolist'

In [61]:

# 
#  WRITTEN BY ChatGPT IN ENTIRETY
#

def print_row(row, index):
    """Prints the row with an index label."""
    print(f"R{index + 1} {row}")
    
# def row_reduce(matrix):
#     num_rows = len(matrix)
#     num_cols = len(matrix[0])
    
#     reduced_matrix = [row[:] for row in matrix]
    
#     for j in range(num_cols):
#         # Find the pivot row
#         pivot_row = max(range(j, num_rows), key=lambda i: abs(reduced_matrix[i][j]), default=None)
        
#         # If the maximum value in the column is 0, move on to the next column
#         if pivot_row is None or reduced_matrix[pivot_row][j] == 0:
#             continue
        
#         # Swap the pivot row with the current row if necessary
#         if pivot_row != j:
#             reduced_matrix[j], reduced_matrix[pivot_row] = reduced_matrix[pivot_row], reduced_matrix[j]
#             print(f"Swap R{j+1} <--> R{pivot_row+1}:")
#             print_matrix(reduced_matrix)
        
#         # Scale the current row so that the pivot is 1
#         pivot = reduced_matrix[j][j]
#         reduced_matrix[j] = [reduced_matrix[j][k] / pivot for k in range(num_cols)]
#         print(f"R{j+1} / {pivot} -> R{j+1}:")
#         print_matrix(reduced_matrix)
        
#         # Eliminate the pivot from all other rows
#         for i in range(num_rows):
#             if i != j:
#                 factor = reduced_matrix[i][j]
#                 reduced_matrix[i] = [reduced_matrix[i][k] - factor * reduced_matrix[j][k] for k in range(num_cols)]
#                 print(f"R{i+1} - ({factor})R{j+1} -> R{i+1}:")
#                 print_matrix(reduced_matrix)
        
#     return reduced_matrix

from fractions import Fraction

from fractions import Fraction

def format_value(val):
    return str(Fraction(val).limit_denominator())

from fractions import Fraction

def print_matrix(matrix):
    for row in matrix:
        print('\t'.join(str(Fraction(val).limit_denominator()) for val in row))
    print('')


def row_reduce(matrix):
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    reduced_matrix = [row[:] for row in matrix]

    for j in range(num_cols):
        # Find the pivot row
        pivot_row = max(range(j, num_rows), key=lambda i: abs(reduced_matrix[i][j]), default=None)

        # If the maximum value in the column is 0, move on to the next column
        if pivot_row is None or reduced_matrix[pivot_row][j] == 0:
            continue

        # Swap the pivot row with the current row if necessary
        if pivot_row != j:
            reduced_matrix[j], reduced_matrix[pivot_row] = reduced_matrix[pivot_row], reduced_matrix[j]
            print(f"Swap R{j+1} <--> R{pivot_row+1}:")
            print_matrix(reduced_matrix)

        # Scale the current row so that the pivot is 1
        pivot = reduced_matrix[j][j]
        reduced_matrix[j] = [reduced_matrix[j][k] / pivot for k in range(num_cols)]
        print(f"R{j+1} / {pivot} -> R{j+1}:")
        print_matrix(reduced_matrix)

        # Eliminate the pivot from all other rows
        for i in range(num_rows):
            if i != j:
                factor = reduced_matrix[i][j]
                reduced_matrix[i] = [reduced_matrix[i][k] - factor * reduced_matrix[j][k] for k in range(num_cols)]
                print(f"R{i+1} - ({factor})R{j+1} -> R{i+1}:")
                print_matrix(reduced_matrix)

    return reduced_matrix







def print_matrix(matrix):
    for row in matrix:
        print('\t'.join('{:.2f}'.format(val) for val in row))
    print('')

# Example usage
matrix = [
    [1, 0, 0, 0, 0, -2],  # K
    [1, 0, -2, 0, 0, 0],  # N
    [0, 12, 0, -1, 0, -1],  # C
    [0, 22, 0, 0, -2, 0],  # H
    [3, 11, 0, -2, -2, -3]  # O
]

# matrix = [
#     [1, 0, -1, 0],
#     [2, 0, -3, -1],
#     [0, 2, 0, -1],
#     [0, 1, 0, -1]
# ]





reduced_matrix = row_reduce(matrix)

if reduced_matrix is not None:
    print("Row-reduced echelon form:")
    print_matrix(reduced_matrix)


Swap R1 <--> R5:
3.00	11.00	0.00	-2.00	-2.00	-3.00
1.00	0.00	-2.00	0.00	0.00	0.00
0.00	12.00	0.00	-1.00	0.00	-1.00
0.00	22.00	0.00	0.00	-2.00	0.00
1.00	0.00	0.00	0.00	0.00	-2.00

R1 / 3 -> R1:
1.00	3.67	0.00	-0.67	-0.67	-1.00
1.00	0.00	-2.00	0.00	0.00	0.00
0.00	12.00	0.00	-1.00	0.00	-1.00
0.00	22.00	0.00	0.00	-2.00	0.00
1.00	0.00	0.00	0.00	0.00	-2.00

R2 - (1)R1 -> R2:
1.00	3.67	0.00	-0.67	-0.67	-1.00
0.00	-3.67	-2.00	0.67	0.67	1.00
0.00	12.00	0.00	-1.00	0.00	-1.00
0.00	22.00	0.00	0.00	-2.00	0.00
1.00	0.00	0.00	0.00	0.00	-2.00

R3 - (0)R1 -> R3:
1.00	3.67	0.00	-0.67	-0.67	-1.00
0.00	-3.67	-2.00	0.67	0.67	1.00
0.00	12.00	0.00	-1.00	0.00	-1.00
0.00	22.00	0.00	0.00	-2.00	0.00
1.00	0.00	0.00	0.00	0.00	-2.00

R4 - (0)R1 -> R4:
1.00	3.67	0.00	-0.67	-0.67	-1.00
0.00	-3.67	-2.00	0.67	0.67	1.00
0.00	12.00	0.00	-1.00	0.00	-1.00
0.00	22.00	0.00	0.00	-2.00	0.00
1.00	0.00	0.00	0.00	0.00	-2.00

R5 - (1)R1 -> R5:
1.00	3.67	0.00	-0.67	-0.67	-1.00
0.00	-3.67	-2.00	0.67	0.67	1.00
0.00	12.00	0.00	-1.00	0

In [2]:
import sympy
import numpy as np

# Define the matrix
# matrix = sympy.Matrix([
#     [1, 0, 0, 0, 0, -2],  # K
#     [1, 0, -2, 0, 0, 0],  # N
#     [0, 12, 0, -1, 0, -1],  # C
#     [0, 22, 0, 0, -2, 0],  # H
#     [3, 11, 0, -2, -2, -3]  # O
# ])
matrix = sympy.Matrix([
    [1, 1, 0, 0, -2, 0],
    [1, 1, 0, -2, 0, 0],
    [0, 3, 4, 0, -4, -1],
    [0, 0, 1, 0, -1, 0]
])

from scipy.linalg import null_space




# Compute the row-reduced echelon form
rref, pivots = matrix.rref()

# Format the result as a matrix
num_rows, num_cols = rref.shape
result = "["
for i in range(num_rows):
    result += "["
    for j in range(num_cols):
        result += f"{rref[i, j]:.2f}"
        if j < num_cols - 1:
            result += ", "
    result += "]"
    if i < num_rows - 1:
        result += "\n "
result += "]"

# Print the result
print("Row-reduced echelon form:\n")
print(result)
print()
print()

matrix = np.array(matrix).astype(np.float64)
ns = null_space(matrix)
print(ns)
print()
print()

minimum = 10000
min_val = None
for i in range(1, 500):
    for j in range(1, 500):
        combo = (i * ns.T[0]) + (j * ns.T[1])
        
        norm = np.linalg.norm(combo)
        ints = True
        for c in np.reshape(combo, (1, np.size(combo)))[0]:
            ints = ints and (np.round(c) - c) < 0.001
            
        if norm < minimum and ints:
            minimum = norm
            min_val = combo
            
print(min_val, minimum)
print('done')

Row-reduced echelon form:

[[1.00, 0.00, 0.00, 0.00, -2.00, 0.33]
 [0.00, 1.00, 0.00, 0.00, 0.00, -0.33]
 [0.00, 0.00, 1.00, 0.00, -1.00, 0.00]
 [0.00, 0.00, 0.00, 1.00, -1.00, 0.00]]


[[ 0.75290675 -0.14890442]
 [ 0.00664557  0.30959045]
 [ 0.37977616  0.08034302]
 [ 0.37977616  0.08034302]
 [ 0.37977616  0.08034302]
 [ 0.01993671  0.92877135]]


[4.36853607 0.34946387 2.35899997 2.35899997 2.35899997 1.04839162] 6.082762530298219
done





________
x5 = t
x4 = 1.57t
x3 = t
x2 = 0.14t
x1 = 2t

<=>

x = t * (2, 0.14, 1, 1.57, 1)^T
200, 140, 100, 156, 100

In [64]:
import numpy as np
from scipy.linalg import null_space
A = np.array([[1, 1], [1, 1]])
ns = null_space(A)
ns * np.sign(ns[0,0])  # Remove the sign ambiguity of the vector

array([[ 0.70710678],
       [-0.70710678]])

In [105]:
mat = [[ 0.75290675, -0.14890442],
      [ 0.00664557,  0.30959045],
      [ 0.37977616,  0.08034302],
      [ 0.37977616,  0.08034302],
      [ 0.37977616,  0.08034302],
      [ 0.01993671,  0.92877135]]

np.reshape(mat, (1, np.size(mat)))[0]

array([ 0.75290675, -0.14890442,  0.00664557,  0.30959045,  0.37977616,
        0.08034302,  0.37977616,  0.08034302,  0.37977616,  0.08034302,
        0.01993671,  0.92877135])

In [107]:
np.round(5.5)

6.0

In [14]:
matrix = sympy.Matrix([
    [1, 0, -1, 0],
    [6, 0, 0, -2],
    [0, 2, -2, 0],
])
matrix = np.array(matrix).astype(np.float64)
ns = null_space(matrix)
print(ns / ns[0])

[[1.]
 [1.]
 [1.]
 [3.]]


In [25]:
matrix = sympy.Matrix([
    [3, 8, 1, -12, -4, -2],
    [1, 0, 0, -1, 0, 0],
    [4, 4, 3, -40, -3, -1],
    [0, 2, 1, -3, -2, 0],
    [0, 1, 0, -12, 0, 0],
])
matrix = np.array(matrix).astype(np.float64)
ns = null_space(matrix)
print(ns)

[[0.02921031]
 [0.35052374]
 [0.61341655]
 [0.02921031]
 [0.61341655]
 [0.35052374]]


In [28]:
(0.2).as_integer_ratio()

(3602879701896397, 18014398509481984)

In [43]:
from fractions import Fraction
Fraction(24.5).limit_denominator()

Fraction(49, 2)

STEPS:

First get the main computational procedure down (below), then worry about the animation (next).
1. Given chemical formula (decide what's a valid input), convert it to matrix
2. Show the steps used to get to RREF. 
3. Show how to use the RREF to compute a basis for the null space.  (https://marksmath.org/classes/Fall2019LinearAlgebra/demos/null_space_basis.html)
4. Use the Fractions class and norm minimization to compute the solution vector.

In [44]:
def row_reduce(matrix):
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    reduced_matrix = [row[:] for row in matrix]

    for j in range(num_cols):
        # Find the pivot row
        pivot_row = max(range(j, num_rows), key=lambda i: abs(reduced_matrix[i][j]), default=None)

        # If the maximum value in the column is 0, move on to the next column
        if pivot_row is None or reduced_matrix[pivot_row][j] == 0:
            continue

        # Swap the pivot row with the current row if necessary
        if pivot_row != j:
            reduced_matrix[j], reduced_matrix[pivot_row] = reduced_matrix[pivot_row], reduced_matrix[j]
            print(f"Swap R{j+1} <--> R{pivot_row+1}:")
            print_matrix(reduced_matrix)

        # Scale the current row so that the pivot is 1
        pivot = reduced_matrix[j][j]
        reduced_matrix[j] = [reduced_matrix[j][k] / pivot for k in range(num_cols)]
        print(f"R{j+1} / {pivot} -> R{j+1}:")
        print_matrix(reduced_matrix)

        # Eliminate the pivot from all other rows
        for i in range(num_rows):
            if i != j:
                factor = reduced_matrix[i][j]
                reduced_matrix[i] = [reduced_matrix[i][k] - factor * reduced_matrix[j][k] for k in range(num_cols)]
                print(f"R{i+1} - ({factor})R{j+1} -> R{i+1}:")
                print_matrix(reduced_matrix)

    return reduced_matrix


def print_matrix(matrix):
    for row in matrix:
        print('\t'.join('{:.2f}'.format(val) for val in row))
    print('')
    
    
matrix = [
    [3, 8, 1, -12, -4, -2],
    [1, 0, 0, -1, 0, 0],
    [4, 4, 3, -40, -3, -1],
    [0, 2, 1, -3, -2, 0],
    [0, 1, 0, -12, 0, 0]
]

reduced_matrix = row_reduce(matrix)

if reduced_matrix is not None:
    print("Row-reduced echelon form:")
    print_matrix(reduced_matrix)


Swap R1 <--> R3:
4.00	4.00	3.00	-40.00	-3.00	-1.00
1.00	0.00	0.00	-1.00	0.00	0.00
3.00	8.00	1.00	-12.00	-4.00	-2.00
0.00	2.00	1.00	-3.00	-2.00	0.00
0.00	1.00	0.00	-12.00	0.00	0.00

R1 / 4 -> R1:
1.00	1.00	0.75	-10.00	-0.75	-0.25
1.00	0.00	0.00	-1.00	0.00	0.00
3.00	8.00	1.00	-12.00	-4.00	-2.00
0.00	2.00	1.00	-3.00	-2.00	0.00
0.00	1.00	0.00	-12.00	0.00	0.00

R2 - (1)R1 -> R2:
1.00	1.00	0.75	-10.00	-0.75	-0.25
0.00	-1.00	-0.75	9.00	0.75	0.25
3.00	8.00	1.00	-12.00	-4.00	-2.00
0.00	2.00	1.00	-3.00	-2.00	0.00
0.00	1.00	0.00	-12.00	0.00	0.00

R3 - (3)R1 -> R3:
1.00	1.00	0.75	-10.00	-0.75	-0.25
0.00	-1.00	-0.75	9.00	0.75	0.25
0.00	5.00	-1.25	18.00	-1.75	-1.25
0.00	2.00	1.00	-3.00	-2.00	0.00
0.00	1.00	0.00	-12.00	0.00	0.00

R4 - (0)R1 -> R4:
1.00	1.00	0.75	-10.00	-0.75	-0.25
0.00	-1.00	-0.75	9.00	0.75	0.25
0.00	5.00	-1.25	18.00	-1.75	-1.25
0.00	2.00	1.00	-3.00	-2.00	0.00
0.00	1.00	0.00	-12.00	0.00	0.00

R5 - (0)R1 -> R5:
1.00	1.00	0.75	-10.00	-0.75	-0.25
0.00	-1.00	-0.75	9.00	0.75	0.25
0.00	5.0

In [48]:
reduced_matrix = np.array(reduced_matrix)
reduced_matrix[0]

array([ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.08333333])

In [13]:
import numpy as np
def linear(u):
    return u

samples = np.linspace(0, 1, 3)
v = np.vstack([samples, linear(samples)]).T.flatten()
v

array([0. , 0. , 0.5, 0.5, 1. , 1. ])

In [20]:
v.reshape([int(len(v) / 2), 2])

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])

In [1]:
name = "Alice"
age = 25
print(f"My name is {name} and I am {age} years old.")


My name is Alice and I am 25 years old.


In [2]:


import pygame

pygame.init()

screen = pygame.display.set_mode((640, 480))
clock = pygame.time.Clock()

image = pygame.image.load('tiktok_logo.png')

theta = 0
while True:
    theta += 6
    rotated_image = pygame.transform.rotate(image, theta)

    rect = rotated_image.get_rect(center=(320, 240))
    rect.x += 100

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()

    screen.fill((255, 255, 255))
    screen.blit(rotated_image, rect)
    pygame.display.flip()

    clock.tick(60)


pygame 2.3.0 (SDL 2.24.2, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html


error: display Surface quit

In [ ]:
    # CLEAN ROTATION EXAMPLE        
        # CLEAN ROTATION EXAMPLE
            # CLEAN ROTATION EXAMPLE
                # CLEAN ROTATION EXAMPLE
                    # CLEAN ROTATION EXAMPLE
    
    
    # Rotation.
            # TODO: Figure out how to do clean rotation, because then you can apply angular velocity for this
            # part of the animation. Honestly? This part is kinda the trickiest bit tbh. Everything else is just
            # drawing parameterized curves of some sort tbh.
            theta = u * 2 * np.pi

            pts = rotate(pts, theta, anchor=center)
            pygame.draw.polygon(window, darkgray, A_many(pts), 0)
            pygame.draw.lines(window, white, False, A_many(pts), width=5)
            rotated_logo = pygame.transform.rotate(logo, np.rad2deg(theta))
            rotated_rekt = rotated_logo.get_rect(center=A(center))
            window.blit(rotated_logo, rotated_rekt) # (0 - (rotated_logo.get_width() / 2), 0 - rotated_logo.get_height() / 2)